### ISSUE TITLE
Check/optimize functionality for non-R code chunks

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/exrcise#7]
Right now, we can't exrcise shell chunks, or chunks without a language specification. It would be handy for our alevin material if we could do that.

**Comment by jashapiro** [comment]
This will probably depend on #6, and will also require some additional functionality to be able to parse comments in other languages that don't use `#` to denote comment lines. 

Will not get done for a bit at this stage.

**Comment by cansavvy** [comment]
It looks like `exrcise` does work for the shell chunks! https://github.com/AlexsLemonade/exercise-notebook-answers/pull/35#discussion_r458460492

So I *think* this issue can be closed?

**Comment by jashapiro** [comment]
I think I will leave it open, as the second part of making it check language and use appropriate comment markers is still relevant. At the least, it should show a warning if used with an unsupported language.
